
name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

env:
  NODE_OPTIONS: --max-old-space-size=4096

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: npx nx-cloud start-ci-run --distribute-on="5 linux-large-plus-js" --stop-agents-after="e2e-ci" --withEnvVars="NODE_OPTIONS"
      - run: yarn
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx lint app1
